extends Node

enum GAME_TIME_STATES {PAUSED, PLAY, END_OF_DAY, GAME_OVER}

enum PLAYER_STATES { MOVE, USE }

enum WEATHER_STATES { SUNNY, CLOUDY, RAINING, SNOWING, STORMING }

enum WEAPON_TYPES { LONG_SWORD, SHORT_SWORD, DAGGER, SPEAR }
enum TOOL_TYPES { AXE, PICKAXE, SHOVEL }
enum INTERACTION_TYPE { NONE, CHEST, FURNACE }
